### ISSUE TITLE
creating a new group

### ISSUE THREAD

**Issue by groovy-d** [jhuckaby/magic-sorting-system#8]
I want to create a new group "fuel" to sort coal, charcoal, bamboo and dried kelp blocks into a chest.
I modified the example group 'dirt' to this, but I don't know it this part is complete.  I know I'll have to go into the data to change the sort for each item away from 'plant' (or coal, or whatever) to fuel.
Is this all I have to do? 

"groups": {
	{
		"group_name": "fuel",
		"item_frame": "minecraft:bamboo",
		"fallback": "misc",
		"items": [
			"minecraft:bamboo",
			"minecraft:coal",
			"minecraft:charcoal",
			"minecraft:dried_kelp_block",
		]
	},
	{
		"group_name": "misc",
		"item_frame": "minecraft:carrot_on_a_stick",
		"items": [
			"minecraft:carrot_on_a_stick"
		]
	}
}

**Comment by jhuckaby** [comment]
Yup, you have the right idea.  Your syntax looks correct I think.  One thing to keep in mind is that each unique item can only live in one group.  So you'll have to make sure that you **remove** the bamboo, coal, charcoal and kelp from their respective groups, and essentially *move* them into your group, so they exist there and only there.  Otherwise the sorting system will get quite confused 😄 

Once that is done, you'll need to install Node.js on your machine, and run the command to read in the config file and regenerate all the Minecraft function files.

Good luck!
