### ISSUE TITLE
Working as intended issue.

### ISSUE THREAD

**Issue by groovy-d** [jhuckaby/magic-sorting-system#9]
running into an ongoing issue with the way minecraft handles item frames and unintentional item elevators.
When I put the item frame onto a hopper and add the item, future items scatter out of it and without containing walls go all over.
If I put the item frame over the hopper so thatthe items 'spill' into the hopper some go in, most go into the block its set on (I tried several trype of blocks, glass, sand, dirt, sprice planks and cobblestone) the majority of the items go into the mounting block and use the block, and blocks above as an item elevator transporting them to the surface.
When I mount the item frame on the ceiling so the items fall down, they instead *all* item elevator upwards.
Part of this stems from an item frame having odd facing.  when we place one, it seems to be the back we see, because the item framed in it shows more out the back than out the front.

I know its not a bug, but its frustrating and makes it very difficult to use, or even want to.
I think this is a great idea and I'll keep playing with it, but I can't help thinking that an item frame, though logical as a target, may not have been the best choice because of MC engine issues.
perhaps a named item placed in a hopper might work? Or marking a chest with a sign that says the item group name? Just tossing ideas out.

If you cannot duplicate this, I'd be happy to extend an invite to my server so you can see it in action and test away.
Thanks!

**Comment by groovy-d** [comment]
addendum,
1. This is on a **realms** server.
2. Now placing the item frame flat on top of the hopper, with at least 2 open air blocks above and a funnel (all 8 surrounding blocks) 2 high prevents the issues above. if you only use 4 blocks to create the funnel at the cardinal point, stuff leaks out.
Its a minecraft thing.
Unfortunatley this means bulk, but its still better than 8 hours of redstone to sort rocks.

**Comment by jhuckaby** [comment]
Ugh, I am very sorry this is happening.  I have never tested on a Realms server, so maybe something is different there, but I've never experienced any of these problems, even on a multiplayer server, unless I flood the system with too many stacks of the same item type at once.

Basically, the limit is effectively 5 stacks of one item (or 5 unique item types) per hopper per category.  So for high traffic groups like stone, dirt and sand, I setup [multiple item frames with multiple hoppers](https://github.com/jhuckaby/magic-sorting-system#multiple-item-frames), so the system load balances between them (each item is teleported to a random matching item frame).  So that way I can drop 10 stacks of each item before it overflows.

In my experience, if a hopper can "accept" an item, it does so instantly, so there is no need to create the funnel system you are talking about.  The only time the system overflows and items fall onto the ground is when the hopper has all 5 of its slots filled, and more items keep coming in.

Again, I apologize for these issues, and I am trying to figure out a better way to do the sort for version 2.0.

**Comment by groovy-d** [comment]
If you want, I'd be glad to send you an invite to my realms server so
you can see how I've set up a full system and tackled certain
challenges.
Just let me know, send me your minecraft name and I'll whitelist you.
Feel free to take screen shots if you want.  I'd also set you up with
our discord so if you want to ask questions or oint things out you'd
be free to.

**Comment by Zottelchen** [comment]
We've got pretty much the same issue on our papermc.io based server. Would be great if there was an alternative to this because on a tree house in the jungle items are flying pretty much everywhere.

**Comment by jhuckaby** [comment]
This should be fixed in v2.0.0 now, if you craft an [auto-drop chest](https://github.com/jhuckaby/magic-sorting-system#advanced) with a redstone clock (it throttles the speed of the item sort, so hoppers should never overload).

Note that 2.0.0 is a major release, and much has changed.  Specifically, there is no longer a chest that replaces itself.  See the [Upgrading from v1.0](https://github.com/jhuckaby/magic-sorting-system#upgrading-from-v10) section for details.
